id: PDC31D7AA
initial_creation_type: input
source_metadata:
  title: Khenchen Ngawang Palzang Series
  language: fr
  description: 'Texts by the great Dzogchen master Khenchen Ngawang Palzang (ngag
    dbang dpal bzang, 1879–1941), also known as Khenpo Ngakchung:'
  volume:
    75005482204a43fc8a57fde05217855d:
      title: Seeds of the Four Philosophical Schools
      parent: Buddhist Philosophy
    bcab3c71e331409eb2e41e6cf716c45d:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Dzogchen
    66859215546b4ac49ae5d2e9c8245ebc:
      title: The Five Wisdoms
      parent: Dzogchen
    bb02e4ca44114d2f95c632e32c61a782:
      title: Prayer to Pema Tötreng Tsal
      parent: Guru Rinpoche Prayers
    4c2ef94663ac475f98bca43088fadf2e:
      title: Brief Succession of Lives Prayer
      parent: Prayers
    cd8b5d54899d46cabb0623c9da467e64:
      title: 'Gyang Lu: A Song of Calling from Afar'
      parent: Prayers
    5de78e0fe774474f9803048ce6adf1c3:
      title: Prayer for this Life, the Next and the Bardos
      parent: Prayers
    b8192f79746b425cbfba624d15e41424:
      title: Prayer to Khenpo Ngawang Palzang
      parent: Prayers
    cd31f8f5dc1b444f9d8d8ee14d4e12b6:
      title: Brief Homage to the Twenty-One Tārās
      parent: Tārā
created_at: '2022-03-01T00:22:24.759245'
last_modified_at: '2022-03-01T00:22:24.759248'
